# Generated by Django 4.1.4 on 2022-12-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_commentpost_commentor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost", options={"verbose_name_plural": "Posts"},
        ),
        migrations.RemoveField(model_name="blogpost", name="slug",),
        migrations.AlterField(
            model_name="commentpost",
            name="body",
            field=models.TextField(verbose_name=""),
        ),
        migrations.AlterField(
            model_name="commentpost",
            name="commentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
