# Generated by Django 4.1.4 on 2022-12-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_commentpost_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostDetails",
            fields=[
                (
                    "blogpost_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogpost",
                    ),
                ),
            ],
            bases=("blog.blogpost",),
        ),
    ]
