# Generated by Django 4.1.4 on 2022-12-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_postdetails"),
    ]

    operations = [
        migrations.DeleteModel(name="PostDetails",),
    ]
