# Generated by Django 4.1.4 on 2023-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_delete_postdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="blog.userprofile"
            ),
        ),
    ]
